---
title: "dataIntegration_file1to13"
output: pdf_document
---

```{r}
library(dplyr)
```

# Read in happiness data
```{r}
happiness2019 = read.csv("data/2019.csv")
happiness2019$year = rep(2019, nrow(happiness2019))
happiness2019 = happiness2019 %>%
  mutate(Country = Country.or.region) %>%
  mutate(Happiness.Score = Score) %>%
  mutate(Economy..GDP.per.Capita. = GDP.per.capita) %>%
  mutate(Family = Social.support) %>%
  mutate(Health..Life.Expectancy. = Healthy.life.expectancy) %>%
  mutate(Freedom = Freedom.to.make.life.choices) %>%
  mutate(Trust..Government.Corruption. = Perceptions.of.corruption) %>%
  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

happiness2018 = read.csv("data/2018.csv")
happiness2018$year = rep(2018, nrow(happiness2018))
happiness2018 = happiness2018 %>%
  mutate(Country = Country.or.region) %>%
  mutate(Happiness.Score = Score) %>%
  mutate(Economy..GDP.per.Capita. = GDP.per.capita) %>%
  mutate(Family = Social.support) %>%
  mutate(Health..Life.Expectancy. = Healthy.life.expectancy) %>%
  mutate(Freedom = Freedom.to.make.life.choices) %>%
  mutate(Trust..Government.Corruption. = Perceptions.of.corruption) %>%
  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

happiness2017 = read.csv("data/2017.csv")
happiness2017$year = rep(2017, nrow(happiness2017))
happiness2017 = happiness2017 %>%
  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

happiness2016 = read.csv("data/2016.csv")
happiness2016$year = rep(2016, nrow(happiness2016))
happiness2016 = happiness2016 %>%
  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

happiness2015 = read.csv("data/2015.csv")
happiness2015$year = rep(2015, nrow(happiness2015))
happiness2015 = happiness2015 %>%
  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

happiness_2015to2019 = rbind(happiness2015, happiness2016, happiness2017, happiness2018, happiness2019)
```


# Read in world health data
```{r}
# 2015, 2019
healthyLifeExpectancy = read.csv("data/HALElifeExpectancyAtBirth.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  mutate(healthyLifeExpectancy = First.Tooltip) %>%
  select(Location, Period, healthyLifeExpectancy)

test <- healthyLifeExpectancy %>%
  ungroup() %>%
  select(Period) %>%
  distinct()

# 2015 to 2018
adolescentBirthRate = read.csv("data/adolescentBirthRate.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(adolescentBirthRate = First.Tooltip) %>%
  select(Location, Period, adolescentBirthRate)

# 2016
airPollutionDeathRate = read.csv("data/airPollutionDeathRate.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(airPollutionDeathRate = First.Tooltip) %>%
  select(Location, Period, airPollutionDeathRate)

# 2015 to 2018
alcoholSubstanceAbuse = read.csv("data/alcoholSubstanceAbuse.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(alcoholSubstanceAbuse = First.Tooltip) %>%
  select(Location, Period, alcoholSubstanceAbuse)

# 2015 to 2017
basicSanitizationServices = read.csv("data/atLeastBasicSanitizationServices.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Total") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(basicSanitizationServices = First.Tooltip) %>%
  select(Location, Period, basicSanitizationServices)

# 2015 to 2017
basicHandwashing = read.csv("data/basicHandWashing.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Total") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(basicHandwashing = First.Tooltip) %>%
  select(Location, Period, basicHandwashing)

# 2015 to 2019
birthsAttendedBySkilledPersonal = read.csv("data/birthAttendedBySkilledPersonal.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(birthsAttendedBySkilledPersonal = First.Tooltip) %>%
  select(Location, Period, birthsAttendedBySkilledPersonal)

# 2015 to 2018
cleanFuelAndTech = read.csv("data/cleanFuelAndTech.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(cleanFuelAndTech = First.Tooltip) %>%
  select(Location, Period, cleanFuelAndTech)

# 2015 to 2016
suicideRates = read.csv("data/crudeSuicideRates.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  filter(Period > 2014) %>%
  #filter(row_number() == 1) %>%
  mutate(suicideRates = First.Tooltip) %>%
  select(Location, Period, suicideRates)

dataAvailabilityForUHC = read.csv("data/dataAvailibilityForUhc.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(Period) %>%
  #filter(row_number() == 1) %>%
  #filter(Period > 2014) %>%
  mutate(dataAvailabilityForUHC = First.Tooltip) %>%
  select(Location, Period, dataAvailabilityForUHC)

# 2015 to 2019
dentistsAvailable = read.csv("data/dentists.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(Period) %>%
  #filter(row_number() == 1) %>%
  filter(Period > 2014) %>%
  mutate(dentistsAvailable = First.Tooltip) %>%
  select(Location, Period, dentistsAvailable)

violenceAgainstWomen = read.csv("data/eliminateViolenceAgainstWomen.csv", stringsAsFactors = TRUE) %>%
  filter(Dim2 == "15-49 years") %>%
  group_by(Location) %>%
  arrange(Period) %>%
  #filter(row_number() == 1) %>%
  #filter(Period > 2014) %>%
  mutate(violenceAgainstWomen = First.Tooltip) %>%
  select(Location, Period, violenceAgainstWomen)
```


# Merge Happiness data with world health data
```{r}
happiness_2015to2019$Location = happiness_2015to2019$Country
happiness_2015to2019$Period = happiness_2015to2019$year
```

```{r}
newHappiness = happiness_2015to2019 %>%
  left_join(probOfDyingFromDisease, by=c("Location", "Period")) %>%
  left_join(adolescentBirthRate, by=c("Location", "Period")) %>%
  left_join(alcoholSubstanceAbuse, by=c("Location", "Period")) %>%
  left_join(basicHandwashing, by=c("Location", "Period")) %>%
  left_join(basicSanitizationServices, by=c("Location", "Period")) %>%
  left_join(birthsAttendedBySkilledPersonal, by=c("Location", "Period")) %>%
  left_join(cleanFuelAndTech, by=c("Location", "Period")) %>%
  left_join(dentistsAvailable, by=c("Location", "Period")) %>%
  left_join(suicideRates, by=c("Location", "Period"))

# Pick before 2019, b/c a lot of our world health data is missing after 2018
newHappiness_pre2019 = newHappiness %>%
  filter(Period < 2019)
```


# Need to figure out if we should drop certain variables based upon number of missing cases
```{r}
colSums(is.na(newHappiness))
colSums(is.na(newHappiness_pre2019))
```


```{r}
rowSums(is.na(newHappiness_pre2019))
```

