---
title: "dataIntegration_file1to13"
output: pdf_document
---

```{r}
library(dplyr)
```

# Read in happiness data
```{r}
happiness2019 = read.csv("data/2019.csv")
happiness2019$year = rep(2019, nrow(happiness2019))
happiness2019 = happiness2019 %>%
  mutate(Location = Country.or.region) %>%
  mutate(Happiness.Score = Score) %>%
  mutate(Economy..GDP.per.Capita. = GDP.per.capita) %>%
  mutate(Family = Social.support) %>%
  mutate(Health..Life.Expectancy. = Healthy.life.expectancy) %>%
  mutate(Freedom = Freedom.to.make.life.choices) %>%
  mutate(Trust..Government.Corruption. = Perceptions.of.corruption) %>%
  select(Location, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

#happiness2018 = read.csv("data/2018.csv")
#happiness2018$year = rep(2018, nrow(happiness2018))
#happiness2018 = happiness2018 %>%
#  mutate(Country = Country.or.region) %>%
#  mutate(Happiness.Score = Score) %>%
#  mutate(Economy..GDP.per.Capita. = GDP.per.capita) %>%
#  mutate(Family = Social.support) %>%
#  mutate(Health..Life.Expectancy. = Healthy.life.expectancy) %>%
#  mutate(Freedom = Freedom.to.make.life.choices) %>%
#  mutate(Trust..Government.Corruption. = Perceptions.of.corruption) %>%
#  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

#happiness2017 = read.csv("data/2017.csv")
#happiness2017$year = rep(2017, nrow(happiness2017))
#happiness2017 = happiness2017 %>%
#  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

#happiness2016 = read.csv("data/2016.csv")
#happiness2016$year = rep(2016, nrow(happiness2016))
#happiness2016 = happiness2016 %>%
#  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

#happiness2015 = read.csv("data/2015.csv")
#happiness2015$year = rep(2015, nrow(happiness2015))
#happiness2015 = happiness2015 %>%
#  select(Country, Happiness.Score, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., year)

#happiness_2015to2019 = rbind(happiness2015, happiness2016, happiness2017, happiness2018, happiness2019)
```


# Read in world health data
```{r}
# 2015 to 2016
probOfDyingFromDisease = read.csv("data/30-70cancerChdEtc.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%  
  filter(row_number() == 1) %>%
  mutate(probOfDyingFromDisease = First.Tooltip) %>%
  select(Location, probOfDyingFromDisease)

# 2015 to 2018
adolescentBirthRate = read.csv("data/adolescentBirthRate.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  mutate(adolescentBirthRate = First.Tooltip) %>%
  select(Location, adolescentBirthRate)

# 2016
airPollutionDeathRate = read.csv("data/airPollutionDeathRate.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  mutate(airPollutionDeathRate = gsub( " .*$", "", First.Tooltip )) %>%
  select(Location, airPollutionDeathRate)

# 2015 to 2018
alcoholSubstanceAbuse = read.csv("data/alcoholSubstanceAbuse.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  mutate(alcoholSubstanceAbuse = First.Tooltip) %>%
  select(Location, alcoholSubstanceAbuse)

# 2015 to 2017
basicSanitizationServices = read.csv("data/atLeastBasicSanitizationServices.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Total") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  mutate(basicSanitizationServices = First.Tooltip) %>%
  select(Location, basicSanitizationServices)

# 2015 to 2017
basicHandwashing = read.csv("data/basicHandWashing.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Total") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  #filter(Period > 2014) %>%
  filter(row_number() == 1) %>%
  mutate(basicHandwashing = First.Tooltip) %>%
  select(Location, basicHandwashing)

# 2015 to 2019
birthsAttendedBySkilledPersonal = read.csv("data/birthAttendedBySkilledPersonal.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  #filter(Period > 2014) %>%
  filter(row_number() == 1) %>%
  mutate(birthsAttendedBySkilledPersonal = First.Tooltip) %>%
  select(Location, birthsAttendedBySkilledPersonal)

# 2015 to 2018
cleanFuelAndTech = read.csv("data/cleanFuelAndTech.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  #filter(Period > 2014) %>%
  filter(row_number() == 1) %>%
  mutate(cleanFuelAndTech = First.Tooltip) %>%
  select(Location, cleanFuelAndTech)

# 2015 to 2016
suicideRates = read.csv("data/crudeSuicideRates.csv", stringsAsFactors = TRUE) %>%
  filter(Dim1 == "Both sexes") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  #filter(Period > 2014) %>%
  filter(row_number() == 1) %>%
  mutate(suicideRates = First.Tooltip) %>%
  select(Location, suicideRates)

dataAvailabilityForUHC = read.csv("data/dataAvailibilityForUhc.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  #filter(Period > 2014) %>%
  mutate(dataAvailabilityForUHC = First.Tooltip) %>%
  select(Location, dataAvailabilityForUHC)

# 2015 to 2019
dentistsAvailable = read.csv("data/dentists.csv", stringsAsFactors = TRUE) %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  #filter(Period > 2014) %>%
  mutate(dentistsAvailable = First.Tooltip) %>%
  select(Location, dentistsAvailable)

violenceAgainstWomen = read.csv("data/eliminateViolenceAgainstWomen.csv", stringsAsFactors = TRUE) %>%
  filter(Dim2 == "15-49 years") %>%
  group_by(Location) %>%
  arrange(desc(Period)) %>%
  filter(row_number() == 1) %>%
  #filter(Period > 2014) %>%
  mutate(violenceAgainstWomen = First.Tooltip) %>%
  select(Location, violenceAgainstWomen)
```


# Merge Happiness data with world health data

```{r}
newHappiness = happiness2019 %>%
  left_join(probOfDyingFromDisease, by=c("Location")) %>%
  left_join(adolescentBirthRate, by=c("Location")) %>%
  left_join(alcoholSubstanceAbuse, by=c("Location")) %>%
  left_join(basicHandwashing, by=c("Location")) %>%
  left_join(basicSanitizationServices, by=c("Location")) %>%
  left_join(birthsAttendedBySkilledPersonal, by=c("Location")) %>%
  left_join(cleanFuelAndTech, by=c("Location")) %>%
  left_join(dentistsAvailable, by=c("Location")) %>%
  left_join(suicideRates, by=c("Location"))
```


# Need to figure out if we should drop certain variables based upon number of missing cases
```{r}
colSums(is.na(newHappiness))
```


```{r}
rowSums(is.na(newHappiness))
```


```{r}
newHappiness_naOmitted = na.omit(newHappiness)
```


# Time for PCA
```{r}
newHappiness.centered.scaled <- scale(newHappiness_naOmitted, center = T, scale = F)
newHappiness.centered.scaled.df <- as.data.frame(newHappiness.centered.scaled)
# Center the data without scaling

newHappiness.pca <- prcomp(newHappiness.centered.scaled.df, scale. = F)
newHappiness.pca.loading <- newHappiness.pca$rotation
# Run PCA and store loadings

knitr::kable(newHappiness.pca.loading)
sum(newHappiness.pca.loading[,1]*newHappiness.pca.loading[,1])
sum(newHappiness.pca.loading[,2]*newHappiness.pca.loading[,2])
# Check that they are unit vectors by calculating their eucledian distance from origin

cor(newHappiness.pca.loading[,1],newHappiness.pca.loading[,2])
# Correlation between loadings
```  

```

